# permissions for end users to view distributedtracings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: distributedtracing-viewer-role
rules:
- apiGroups:
  - backend.tracingshift
  resources:
  - distributedtracings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - backend.tracingshift
  resources:
  - distributedtracings/status
  verbs:
  - get
